/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/

IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFF')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFF', '', 'AEFUIE', 1, '2016-06-01 00:00:01.000', 0, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UIE')


/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFE')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFE', '', 'AEFUPE', 1, '2016-06-01 00:00:01.000', 0, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UPE')


/* 
	INSERT Record into AEF_LINK for the weekly summary reminder email
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFD')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFD', '', 'AEFSWR', 1, '2016-06-01 00:00:01.000', 0, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_SWR')