UPDATE CONTACTS SET CT_EMAIL = 'tony.tasker@businesscareare.co.uk' WHERE CT_EMAIL IS NOT NULL
UPDATE MBRFILE SET MBR_EMAIL = 'tony.tasker@bcluk.com' WHERE MBR_EMAIL IS NOT NULL
UPDATE MBRFILE SET MBR_CEMAIL = 'tony.tasker@bcluk.com' WHERE MBR_CEMAIL IS NOT NULL

