DECLARE @FuncNo VARCHAR(7) = 'INSERT FUNCTION REFERENCE'

-- FUNCTION CHARGE DETAIL
SELECT F_REF AS FunctionRef, F_ROOM AS Room, ISNULL(F_RM_CHG, 0) AS RoomCharge
FROM FUNC_FIL
WHERE F_REF = @FuncNo
		AND F_RM_CHG <> 0
		AND F_CUT <> 1
		AND F_OFFRM <> 1
		AND F_POSTED = 0
		AND ( F_OWNER IS NULL
			OR F_OWNER = ''
			OR F_OWNER = F_REF ) 

-- EXTRAS CHARGES DETAILS
SELECT AI_CODE AS ExtraCode, AI_COVERS AS Covers, AI_CHARGE AS Charge, ISNULL(AI_COVERS * AI_CHARGE, 0) AS TotalExtraCharge
FROM FUNC_FIL, AI_FILE, POST_DEF
WHERE AI_FREF = @FuncNo
		AND AI_FREF = F_REF
		AND P_CODE = AI_CODE
		AND AI_CHARGE <> 0
		AND AI_POSTED = 0
		AND NOT ( P_COSTCENT = 'CCPAID' )

-- PACKAGE CHARGES DETAILS
SELECT PH_CODE AS PackageCode, PH_DESC as PackageDescription, PH_PRICE AS PackageCharge, PH_COVERS AS Covers, ISNULL(PH_PRICE * PH_COVERS, 0) AS TotalPackageCharge
FROM FUNC_FIL, PKGHEAD
WHERE PH_OWNER = @FuncNo
		AND F_REF    = PH_OWNER 
		AND PH_POSTED = 0 

-- MENU CHARGES DETAILS
SELECT MNM_NAME AS MenuName, MNM_PRICE AS MenuPrice, ISNULL(MNM_PRICE, 0) AS TotalMenuCharge
FROM FUNC_FIL, MASTMENU
WHERE MNM_OWNER = @FuncNo
		AND MNM_OWNER = F_REF
		AND MNM_PRICE <> 0
		AND MNM_POSTED = 0

