-- =====================================================================================================
-- Author:		Tony Tasker
-- Create date: 05/12/2016
-- Description:	This stored procedure configures CABS AutoEMail for Clayton Utz
--
-- =====================================================================================================
-- Version:		1
-- Date:		05/12/2016
-- =====================================================================================================
-- Changes:	TT: 05/12/2016: Original Version
--  (1)
-- =====================================================================================================
SET NOCOUNT ON 
GO
 
IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'SYS' AND ST_CODE = 'AET') = 0
BEGIN
	PRINT 'Adding AutoEMail Section AET in Descriptions and Code'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AET', 'SYS', 'Auto-Email Templates', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Section AET ALready Exists in Descriptions and Code'
END

IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'AET' AND ST_CODE = 'AEFUPD') = 0
BEGIN
	PRINT 'Adding AutoEMail Template Description AEFUPD'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AEFUPD', 'AET', 'Booking Update', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Template Description AEFUPD Already Ready Exists'
END


IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AddFuncRefToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AddHostToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AdminEmailAddr') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AdminEmailAddr', 'INSERT EMAIL ADDRESS', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AttachCalendarFile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AttachCalendarFile', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Bullet01') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Bullet01', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Company') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Company', 'Clayton Utz', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'CurrencySymbol') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'CurrencySymbol', '$', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DebugFlag') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DebugFlag', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontColorDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontColorDel', 'Red', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontSizeDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontSizeDel', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontTypeDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontTypeDel', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontWeightDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontWeightDel', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFormat') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFormat', 'HTML', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontWeight', 'Bold', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailProfile', 'CustomerServicesNoReply', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalut', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignature', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailType', 'S', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Enabled') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Enabled', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'ExtraCCToInclude') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'ExtraCCToInclude', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'FileAttachments') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'FileAttachments', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'FirstRunDate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'FirstRunDate', '01/01/2016', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Frequency', 'D:2;H:0;M:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HiddenRoomText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HiddenRoomText', 'Room will be notified <H> hours in advance', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HideRoom') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HideRoom', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HideRoomGivenOverride') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HideRoomGivenOverride', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Importance') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Importance', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeAttachments') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeAttachments', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerMBRNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerMBRNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerMBRTel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerMBRTel', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerName') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerName', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookingStatus') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookingStatus', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeHostMBRNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeHostMBRNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeHostMBRTel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeHostMBRTel', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeMeetingType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeMeetingType', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeOtherSessionDetails') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeOtherSessionDetails', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeSessNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeSessNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeSubjectInBody') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeSubjectInBody', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeWeekends') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeWeekends', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'LayoutNumber') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'LayoutNumber', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'OnlyIncludeAssignedExtras') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'OnlyIncludeAssignedExtras', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendOnWeekends') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendOnWeekends', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToBooker') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToBooker', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToDepartment') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToDepartment', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToHost') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToHost', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Sensitivity') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Sensitivity', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SubjectLine', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'UseJobTitleForMBRIntern') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'UseJobTitleForMBRIntern', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'UseMBRInternForNames') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'UseMBRInternForNames', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'WIPWIndow') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'WIPWIndow', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'AgedFunctionInDays') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'AgedFunctionInDays', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'DebugFlag') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'DebugFlag', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'Enabled') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'Enabled', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'AddFuncRefToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'AddHostToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'CreateDayCutOff') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'CreateDayCutOff', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'DetailHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'DetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailBodyText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailBodyText', 'Changes have been made to Function **FREF**. Please review ALL of the following details:', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailHeaderText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailProfile', 'INSERT PROFILE NAME', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailSalut', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailSignature', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailSPROC') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailSPROC', 'CABS_AUTO_EMAIL_FUNCS_SEND', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EmailSubTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EnabledB') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EnabledB', 'I:0;U:1;D:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'EnabledE') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'EnabledE', 'I:0;U:1;D:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'Frequency', 'D:0;H:0;M:3;W:1;L:CR;', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'IncOtherSession') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'IncOtherSession', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'LayoutNumber') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'LayoutNumber', '2', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'OnlySendRoomGiven') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'OnlySendRoomGiven', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'OnlySendRoomUpdate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'OnlySendRoomUpdate', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'SendToClient') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'SendToClient', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'SendToLocation') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'SendToLocation', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'StatusCode') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'StatusCode', 'CONFRM', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFUPD' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFUPD', 'SubjectLine', 'AMENDED BOOKING:', '0', 'cc', GETUTCDATE())
END
GO



/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/

IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFF')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFF', '', 'AEFUIE', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UIE')


/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFE')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFE', '', 'AEFUPE', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UPE')


/* 
	INSERT Record into AEF_LINK for the weekly summary reminder email
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFD')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFD', '', 'AEFSWR', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_SWR')