-- =====================================================================================================
-- Author:		Tony Tasker
-- Create date: 30/11/2016
-- Description:	This stored procedure configures CABS AutoEMail for PwC Oz
--
-- =====================================================================================================
-- Version:		1
-- Date:		30/11/2016
-- =====================================================================================================
-- Changes:	TT: 30/11/2016: Original Version
--  (1)
-- =====================================================================================================
SET NOCOUNT ON 
GO
 
IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'SYS' AND ST_CODE = 'AET') = 0
BEGIN
	PRINT 'Adding AutoEMail Section AET in Descriptions and Code'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AET', 'SYS', 'Auto-Email Templates', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Section AET ALready Exists in Descriptions and Code'
END

IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'AET' AND ST_CODE = 'AEFSTC') = 0
BEGIN
	PRINT 'Adding AutoEMail Template Description AEFSTC'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AEFSTC', 'AET', 'Booking Status Change', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Template Description AEFSTC Already Ready Exists'
END

IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'AET' AND ST_CODE = 'AEFSWR') = 0
BEGIN
	PRINT 'Adding AutoEMail Template Description AEFSWR'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AEFSWR', 'AET', 'Summary Weekly Reminder', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Template Description AEFSWR Already Ready Exists'
END

IF (SELECT COUNT(*) FROM SYS_ABBR WHERE ST_TYPE = 'AET' AND ST_CODE = 'AEFDRM') = 0
BEGIN
	PRINT 'Adding AutoEMail Template Description AEFDRM'
	INSERT INTO SYS_ABBR
	(ST_CODE, ST_TYPE, ST_DESC, ST_IN_USE, ST_DIRYPOS, ST_LOC, ST_CANPOST, ST_FILTER_TYPE)
	VALUES
	('AEFDRM', 'AET', 'Individual Booking Reminder', 0, NULL, NULL, NULL, NULL)
END
ELSE
BEGIN
	PRINT 'AutoEMail Template Description AEFDRM Already Ready Exists'
END


IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'AddFuncRefToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'AddHostToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'CreateDayCutOff') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'CreateDayCutOff', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'DetailHeading', 'This is your final confirmation for your function.  Please carefully check all details listed below and advise us immediately of any changes.<br><br>Key items to remember:<br><br>- Catering / Alcohol requirements need to be confirmed by 12pm tomorrow.<br>- Please inform us of any special dietary requirements - names and specifics<br>- If your function has Audio Visual requirements, please check all equipment is booked and advise whether AV support is required.<br>- Please ensure room layout is specified - Please note special floor plans need to be received by today.<br>- Please ensure that all visitors are registered for security access/visitor passes (including interstate & international PwC staff).', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'DetailSubHeading', 'It is essential that you check with reception before proceeding to your room as all bookings can be subject to last minute room changes.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailBodyText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailBodyText', 'Current Booking Details:', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailHeaderText', 'SUMMARY OF FINAL DETAILS', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailProfile', 'CustomerServicesNoReply', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailSalut', 'Please advise any amendments by email to **BSITE** Reception.<BR><BR>Regards', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailSignature', ' **BSITE** Reception.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailSPROC') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailSPROC', 'CABS_AEF_SEND_DRM', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'EmailSubTitle', 'Dear **FNAME**', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'Enabled') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'Enabled', 'I:1;U:1;D:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'Frequency', 'D:0;H:0;M:1;W:1;L:CR;', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'FrequencyA') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'FrequencyA', 'D:3;H:0;M:0;W:1;L:B4;', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'OnlySendRoomGiven') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'OnlySendRoomGiven', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'OnlySendRoomUpdate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'OnlySendRoomUpdate', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'SendToBooker') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'SendToBooker', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'StatusCode') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'StatusCode', 'CONFRM', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFDRM' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFDRM', 'SubjectLine', 'Confirm Details - Booking Ref: ', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'AddFuncRefToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'AddHostToSubject', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'CreateDayCutOff') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'CreateDayCutOff', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'DetailHeading', 'This is a notification that the status of your booking has changed. ', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'DetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailBodyText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailBodyText', 'Current Booking Details:', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailHeaderText', 'BOOKING STATUS CHANGE', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailProfile', 'CustomerServicesNoReply', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailSalut', 'Please advise any amendments by email to **BSITE** Reception.<BR><BR>Regards', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailSignature', ' **BSITE** Reception.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailSPROC') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailSPROC', 'CABS_AEF_SEND_DRM', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EmailSubTitle', 'Dear **FNAME**', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'EnabledB') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'EnabledB', 'I:0;U:1;D:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'Frequency', 'D:0;H:0;M:1;W:1;L:CR;', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'OnlySendRoomGiven') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'OnlySendRoomGiven', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'OnlySendRoomUpdate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'OnlySendRoomUpdate', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'SendToBooker') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'SendToBooker', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'StatusCode') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'StatusCode', 'CONFRM,PROVNL,CANCEL,OFF', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSTC' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSTC', 'SubjectLine', 'Booking Status Change', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'AddFuncRefToSubject', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'AddHostToSubject', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'CreateDayCutOff') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'CreateDayCutOff', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'DetailHeading', 'Your bookings over the next week are detailed below.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'DetailSubHeading', 'Please take one of the following actions:<BR><BR>1. Click the “My Bookings” link below to access the online room booking system to cancel/amend your booking (s): <BR><BR>**LINK**<br><br>Or<BR><BR>2. Please advise **BSITE** reception by email, quoting the relevant reference number.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailBodyText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailBodyText', 'Summary of Bookings:', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailHeaderText', ' ', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailProfile', 'CustomerServicesNoReply', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailSalut', 'Key Items to remember:<BR><BR>- All catering/alcohol requirements need to be confirmed.<BR>- Please ensure that all visitors are registered for security access/visitor pass (including interstate & international PwC staff).<BR><BR>For further assistance, please contact the Reservations team.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailSignature', ' **BSITE** Reception.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailSPROC') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailSPROC', 'CABS_AEF_SEND_SWR', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EmailSubTitle', 'Dear **FNAME**, <BR><BR>You have a reservation scheduled for next week. Please confirm your booking is still proceeding and all details listed below are correct.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'EnabledB') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'EnabledB', 'I:1;U:0;D:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'Frequency', 'D:0;H:0;M:0;S:2;T:0900;L:RE', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'HyperLink1') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'HyperLink1', 'http://www.bbc.co.uk', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'HyperLink1_DisplayText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'HyperLink1_DisplayText', 'My Bookings', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'OnlySendRoomGiven') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'OnlySendRoomGiven', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'OnlySendRoomUpdate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'OnlySendRoomUpdate', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'ReportDurationInDays') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'ReportDurationInDays', '7', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'ReportStartFromNowInDays') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'ReportStartFromNowInDays', '7', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'SendToBooker') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'SendToBooker', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'StatusCode') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'StatusCode', 'CONFRM', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'AEFSWR' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'AEFSWR', 'SubjectLine', 'Please Check Your Weekly Summary of Upcoming Meetings', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AddFuncRefToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AddFuncRefToSubject', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AddHostToSubject') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AddHostToSubject', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AdminEmailAddr') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AdminEmailAddr', 'tony.tasker@bcluk.com', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'AttachCalendarFile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'AttachCalendarFile', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Bullet01') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Bullet01', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Company') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Company', '[PriceWaterhouseCooper]', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'CurrencySymbol') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'CurrencySymbol', '$', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeading', 'Please ensure all the details shown below are correct. If you notice that any amendments are required, contact quoting the Reference Number.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailHeadingFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailHeadingFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'DetailSubHeadingFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'DetailSubHeadingFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontColorDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontColorDel', 'Red', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontSizeDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontSizeDel', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontTypeDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontTypeDel', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailBodyFontWeightDel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailBodyFontWeightDel', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFooterTextFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFooterTextFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailFormat') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailFormat', 'HTML', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailHeaderTextFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailHeaderTextFontWeight', 'Bold', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailProfile') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailProfile', 'CustomerServicesNoReply', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalut') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalut', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSalutFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSalutFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignature') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignature', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSignatureFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSignatureFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailSubTitleFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailSubTitleFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontColor') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontColor', 'Black', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontSize') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontSize', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontType', 'Arial', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailTitleFontWeight') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailTitleFontWeight', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'EmailType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'EmailType', 'S', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Enabled') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Enabled', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'ExtraCCToInclude') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'ExtraCCToInclude', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'FileAttachments') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'FileAttachments', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'FirstRunDate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'FirstRunDate', '01/01/2016', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Frequency') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Frequency', 'D:2;H:0;M:0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HiddenRoomText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HiddenRoomText', 'Room will be notified <H> hours in advance', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HideRoom') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HideRoom', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'HideRoomGivenOverride') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'HideRoomGivenOverride', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Importance') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Importance', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeAttachments') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeAttachments', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerMBRNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerMBRNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerMBRTel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerMBRTel', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookerName') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookerName', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeBookingStatus') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeBookingStatus', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeHostMBRNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeHostMBRNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeHostMBRTel') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeHostMBRTel', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeMeetingType') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeMeetingType', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeOtherSessionDetails') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeOtherSessionDetails', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeSessNo') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeSessNo', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeSubjectInBody') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeSubjectInBody', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'IncludeWeekends') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'IncludeWeekends', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'LayoutNumber') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'LayoutNumber', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'OnlyIncludeAssignedExtras') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'OnlyIncludeAssignedExtras', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendOnWeekends') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendOnWeekends', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToBooker') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToBooker', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToDepartment') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToDepartment', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SendToHost') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SendToHost', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'Sensitivity') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'Sensitivity', 'Normal', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'SubjectLine') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'SubjectLine', 'Booking Reference and Host:', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'UseJobTitleForMBRIntern') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'UseJobTitleForMBRIntern', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'UseMBRInternForNames') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'UseMBRInternForNames', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS' AND [KEY] = 'WIPWIndow') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS', 'WIPWIndow', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'AgedFunctionInDays') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'AgedFunctionInDays', '10', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'DetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'DetailHeading', 'Please ensure you read through all the details below. If you have any queries, please contact the Catering team on ____________.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'DetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'DetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'EmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'EmailHeaderText', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'EmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'EmailSubTitle', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'Enabled') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'Enabled', '0', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'OnlySendBookerUpdate') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'OnlySendBookerUpdate', '1', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'SessionDetailHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'SessionDetailHeading', 'Please ensure you read through all the details below. If you have any queries, please contact the Catering team on ____________.', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'SessionDetailSubHeading') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'SessionDetailSubHeading', '', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'SessionEmailHeaderText') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'SessionEmailHeaderText', 'RESERVATION NOTIFICATION', '0', 'cc', GETUTCDATE())
END
GO
IF (SELECT COUNT(*) FROM xCABS_CONFIG_TABLE WHERE [DELETED] = 0 AND [SECTION] = 'CABS_AUTO_EMAIL_FUNCS_Trigger' AND [KEY] = 'SessionEmailSubTitle') = 0 
BEGIN 
INSERT INTO xCABS_CONFIG_TABLE
([TYPE], [SOURCE], [SECTION], [KEY], [VALUE], [DELETED], [CHANGE_BY], [CHANGE_UTC])
VALUES
('S', '', 'CABS_AUTO_EMAIL_FUNCS_Trigger', 'SessionEmailSubTitle', '', '0', 'cc', GETUTCDATE())
END
GO

/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/

IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFF')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFF', '', 'AEFUIE', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UIE')


/* 
	INSERT Record into AEF_LINK for the weekly report email for Uninvoiced Event
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFE')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFE', '', 'AEFUPE', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_UPE')


/* 
	INSERT Record into AEF_LINK for the weekly summary reminder email
*/
IF NOT EXISTS (SELECT AEFL_FREF FROM AEF_LINK WHERE AEFL_FREF = 'FFFFFFD')
	INSERT INTO AEF_LINK
		(AEFL_FREF, AEFL_SessNo, AEFL_EmailType, AEFL_CanSend, AEFL_FDay, AEFL_SENT, AEFL_SendTime, AEFL_Source, AEFL_Department, AEFL_EmailSPROC)
		VALUES ('FFFFFFD', '', 'AEFSWR', 1, '2016-06-01 00:00:01.000', 1, '2016-06-15 09:30:00', 'UPDATE:STATUS', 'CCHIRE', 'CABS_AEF_SEND_SWR')