
/****** Object:  View [dbo].[vw_FOL_TRAN_CRED_SUMMARY]    Script Date: 25/09/2016 17:02:23 ******/
if exists (Select object_id from sys.objects where name = 'vw_FOL_TRAN_CRED_SUMMARY') begin
	DROP VIEW [dbo].[vw_FOL_TRAN_CRED_SUMMARY]
END
GO

/****** Object:  View [dbo].[vw_FOL_TRAN_CRED_SUMMARY]    Script Date: 25/09/2016 17:02:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/* SELECT * FROM [dbo].[FOL_TRAN];*/
CREATE VIEW [dbo].[vw_FOL_TRAN_CRED_SUMMARY]
AS
SELECT  F_SOURCE, F_OWNER, F_ONINV, F_CREDIT, P_COSTCENT, F_VAT_CODE,  ST_DESC, P_NL_CODE, F_TRANSFRD, 
		ROUND(SUM(ROUND(CAST(FOL_TRAN.F_COST AS Money), 2)*-1), 2) AS COST, 
		ROUND(SUM(ROUND(CAST(FOL_TRAN.F_VALUE AS money), 2))*-1, 2) AS VALUE, 
        ROUND(SUM(CAST(FOL_TRAN.F_VAT_AMT AS money))*-1, 2) AS VATAMT, 
		MAX(FOL_TRAN.F_TRANNO) AS F_TRANNO, 
		MAX(FOL_TRAN.F_DATE) AS F_DATE, MAX(FOL_TRAN.F_POSTCODE) AS F_POSTCODE, 
		MAX(FOL_TRAN.F_NOWSHOW) AS F_NOWSHOW, MAX(FOL_TRAN.F_VAT_RATE) AS F_VAT_RATE,  
		MAX(FOL_TRAN.F_INVDATE) AS F_INVDATE, MAX(FOL_TRAN.F_CHARGEBK) AS F_CHARGEBK, 
		MAX(FOL_TRAN.F_DOCKET) AS F_DOCKET, MAX(FOL_TRAN.F_PAIDBY) AS F_PAIDBY, 
		MAX(FOL_TRAN.F_PAIDON) AS F_PAIDON, MAX(isnull(FOL_TRAN.F_CLIENT,'')) AS F_CLIENT, 
        MAX(FOL_TRAN.F_MATTER) AS F_MATTER, MAX(FOL_TRAN.F_ITEMTYPE) AS F_ITEMTYPE, 
		MAX(FOL_TRAN.F_POSTDATE) AS F_POSTDATE, MAX(FOL_TRAN.F_TRANSFRD_PAID) AS F_TRANSFRD_PAID, 
		MAX(FOL_TRAN.F_TRANSFRD_XML) AS F_TRANSFRD_XML, 
		ROUND(SUM(ROUND(CAST(FOL_TRAN.F_CALCAMT AS money), 2))*-1, 2) AS F_CALC_AMT, 
		dbo.uf_getExtClientRef(Fol_tran.F_SOURCE) AS ExtCliRef ,
			  COUNT(ItemCount) as ItemCount
FROM           vw_netted_Foltran AS Fol_tran INNER JOIN
                         SYS_ABBR ON P_COSTCENT = SYS_ABBR.ST_CODE
GROUP BY Fol_tran.F_SOURCE, F_OWNER, FOL_TRAN.F_ONINV, FOL_TRAN.F_CREDIT, P_COSTCENT, FOL_TRAN.F_VAT_CODE,
                         SYS_ABBR.ST_DESC, P_NL_CODE, F_TRANSFRD
--FOL_TRAN.F_POSTCODE, 
HAVING        (ROUND(SUM(ROUND(CAST(FOL_TRAN.F_CALCAMT AS money), 2)), 2) < 0)



GO


